
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-07-27T12:02:04+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "165103e3f25d5a093926de20af97689f2fba7805",
 "version": "0.5.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
